apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: ei-backend
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployments.backend.replicaCount }}
  selector:
    matchLabels:
      name: ei-backend
      app: ei
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        name: ei-backend
        app: ei
        elasticGrokFilter: {{ .Values.deployments.backend.elasticGrokFilter }}
    spec:
      volumes:
        - name: log4j
          configMap:
            name: ei-log4j
      imagePullSecrets:
        - name: regcred
      containers:
        - name: skltp-ei-backend
          image: "{{ .Values.repository }}skltp-ei-backend:{{ .Values.container.backend.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.backend.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/ei
              name: log4j
          ports:
            - containerPort: 8082
              protocol: TCP
              name: backend-tcp1
            - containerPort: 8083
              protocol: TCP
              name: backend-tcp2
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/liveness
              port: 8881
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/readiness
              port: 8881
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            {{- range $.Values.environment.backend._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.backend.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.backend.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}