apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: ei-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployments.frontend.replicaCount }}
  selector:
    matchLabels:
      name: ei-frontend
      app: ei
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        name: ei-frontend
        app: ei
        app.kubernetes.io/name: ei-frontend
        elasticGrokFilter: {{ .Values.deployments.frontend.elasticGrokFilter }}
    spec:
      volumes:
        - name: log4j
          configMap:
            name: ei-log4j
      imagePullSecrets:
        - name: regcred
      containers:
        - name: skltp-ei-frontend
          image: "{{ .Values.repository }}skltp-ei-frontend:{{ .Values.container.frontend.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.frontend.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/ei
              name: log4j
          ports:
            - containerPort: 8081
              protocol: TCP
              name: frontend-tcp1
            - containerPort: 8084
              protocol: TCP
              name: frontend-tcp2
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/liveness
              port: 8882
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/readiness
              port: 8882
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.frontend_resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            {{- range $.Values.environment.frontend._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.frontend.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.frontend.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}