apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: ei-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ei-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: ei-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: skltp-ei-frontend
          image: "{{ .Values.repository }}skltp-ei-frontend:{{ .Values.container.frontend.image.tag | default $.Chart.AppVersion }}"
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
          livenessProbe:
            failureThreshold: 15
            httpGet:
              path: skltp-ei-frontend/status
              port: 8084
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: skltp-ei-frontend/status
              port: 8084
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 801m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 401Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            {{- range $.Values.environment.frontend._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.frontend.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.frontend.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}