apiVersion: v1
kind: ConfigMap
metadata:
  name: ei-backend-configmap-default
data:
  # Used for hawtio (http://localhost:8881/actuator/hawtio/)
  SERVER_PORT: "8881"

  # Webservices urls
  FINDCONTENT_WEBSERVICE_URL: http://0.0.0.0:8082/skltp-ei/find-content-service/v1

  # The engagement index own HSA ID, the same as owner
  EI_HSA_ID: "5565594230"

  # VP properties for calling VP services
  VP_HSA_ID: "5565594230"
  VP_INSTANCE_ID: {{ .Values.skltp.instanceId }}

  # Properties to call GetLogicalAddresseesByServiceContract
  GETLOGICALADDRESSES_SERVICEENDPOINTURL: http://vp:8080/vp/infrastructure/itintegration/registry/GetLogicalAddresseesByServiceContract/2/rivtabp21
  GETLOGICALADDRESSES_CONNECTTIMEOUTMS: "5000"
  GETLOGICALADDRESSES_REQUESTTIMEOUTMS: "5000"

  # Properties to call ProcessNotification
  PROCESSNOTIFICATION_SERVICEENDPOINTURL: http://vp:8080/vp/ProcessNotification/1/rivtabp21

  # Subscriber local file cache
  SUBSCRIBER_CACHE_FILE_NAME: /tmp/ei.localCache3
  SUBSCRIBER_CACHE_TIMETOLIVESECONDS: "30000"
  SUBSCRIBER_CACHE_RESET_URL: http://0.0.0.0:8083/skltp-ei/resetcache
  SUBSCRIBER_CACHE_STATUS_URL: http://0.0.0.0:8083/skltp-ei/subscriber/status

  # Status service URL
  EI_STATUS_URL: http://0.0.0.0:8083/skltp-ei-backend/status

  # Activemq properties
  # K8S DevNote: This dot notation is a nicer looking format for keys.
  activemq.broker.url: failover:(tcp://ei-amq:61616)?randomize=false&timeout=10000&jms.prefetchPolicy.queuePrefetch=5
  # ACTIVEMQ_BROKER_USER:
  # ACTIVEMQ_BROKER_PASSWORD:
  ACTIVEMQ_BROKER_MAXIMUM-REDELIVERIES: "5"
  ACTIVEMQ_BROKER_REDELIVERY_DELAY: "60000"
  ACTIVEMQ_BROKER_BACKOFF_MULTIPLIER: "5"
  ACTIVEMQ_BROKER_USE_EXPONENTIAL_BACKOFF: "true"

  # MySQL settings
  spring.datasource.url: jdbc:mysql://localhost:3306/ei_test_amq?serverTimezone=Europe/Stockholm
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
  SPRING_DATASOURCE_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
  SPRING_DATASOURCE_JPA_HIBERNATE_DDL-AUTO: update