apiVersion: v1
kind: ConfigMap
metadata:
  name: ei-frontend-configmap-default
data:
  LOGGING_CONFIG: "{{ .Values.paths.loggingConfig }}"

  # Actuator settings
  SERVER_PORT: "{{ .Values.frontend.server.port }}"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "{{ .Values.management.endpointsWebExposureInclude }}"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "{{ .Values.management.endpointPrometheusEnabled }}"

  # Webservices urls
  UPDATE_WEBSERVICE_URL: "{{ .Values.frontend.update.webserviceUrl }}"
  PROCESSNOTIFICATION_WEBSERVICE_URL: "{{ .Values.frontend.processNotification.webserviceUrl }}"

  # Status service URL
  EI_STATUS_URL: "{{ .Values.frontend.statusUrl }}"

  # The engagement index own HSA ID, the same as owner
  EI_HSA_ID: "{{ .Values.ei.hsaId }}"

  # The HSA ID used when communicating with service platform, e.g GetLogicalAddresseesByServiceContract.
  VP_HSA_ID: "{{ .Values.vp.hsaId }}"

  # A list of HSA-ID known to not be allowed for usage as logical-address nor source-system in calls to the services Update and ProcessNotification.
  # This list is used to avoid the possibility to introduce looping aggregating services that is tricked to call it self without end...
  UPDATE-NOTIFICATION_NOT_ALLOWED_HSAID_LIST: "{{ .Values.frontend.updateNotification.notAllowedHsaidList }}"

  {{- if .Values.queues.prefix }}
  # ActiveMQ queue names
  COLLECT_QUEUE_NAME: "{{ .Values.queues.prefix }}.collect"
  PROCESS_QUEUE_NAME: "{{ .Values.queues.prefix }}.process"
  {{- end }}

  # AMQ broker property
  ACTIVEMQ_BROKER_URL: "{{ .Values.activemq.broker.url }}"
  ACTIVEMQ_BROKER_MAXIMUM-REDELIVERIES: "{{ .Values.activemq.broker.maximumRedeliveries }}"
  ACTIVEMQ_BROKER_REDELIVERY_DELAY: "{{ .Values.activemq.broker.redeliveryDelay }}"
