apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ei-log4j
data:
  log4j2.xml: |
    <Configuration status="WARN" monitorInterval="30">

      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <EcsLayout/>
        </Console>
      </Appenders>

      <Loggers>
        {{- range .Values.log4j.loggers }}
        <AsyncLogger name="{{ .name }}" level="{{ .level }}"/>
        {{- end }}
  
        <AsyncRoot level="{{ .Values.log4j.rootLoggerLevel }}">
          <AppenderRef ref="Console"/>
        </AsyncRoot>
      </Loggers>
    </Configuration>
