apiVersion: v1
kind: Service
metadata:
  name: ei-backend
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: webservice
  - port: 8083
    protocol: TCP
    targetPort: 8083
    name: status
  selector:
    name: ei-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}