apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vip.name }}
spec:
  selector:
    app: ei
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: frontend-tcp1
      protocol: TCP
      name: http-frontend
    - port: 8082
      targetPort: backend-tcp1
      protocol: TCP
      name: http-backend
status:
  loadBalancer: {}
