apiVersion: v1
kind: Service
metadata:
  name: ei-frontend
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: webservice
  - port: 8084
    protocol: TCP
    targetPort: 8084
    name: status
  selector:
    name: ei-frontend
  sessionAffinity: None
  type: ClusterIP