repository: docker.drift.inera.se/ntjp/

container:
  backend:
    image:
      tag: # Override to supply another image tag to run
      pullPolicy: Always
  frontend:
    image:
      tag: # Override to supply another image tag to run
      pullPolicy: Always

# Environment-specific backwards-compatible service name
vip:
  name: default-ei-vip

queues:
  prefix: # Override to apply common queue naming

deployments:
  backend:
    replicaCount: 1
    elasticGrokFilter: camel
  frontend:
    replicaCount: 1
    elasticGrokFilter: camel

environment:
  backend:
    _default_config_maps:
      - ei-backend-configmap-default
    config_maps:
      # Override to supply your own maps.
    secrets:
      # Override to supply your own secrets.
  frontend:
    _default_config_maps:
      - ei-frontend-configmap-default
    config_maps:
      # Override to supply your own maps.
    secrets:
      # Override to supply your own secrets.

log4j:
  loggers:
    - name: se.skltp.ei
      level: INFO
    - name: se.skltp.ei.subscriber
      level: INFO
    - name: se.skltp.ei.service.GetLogicalAddresseesServiceClient
      level: WARN
    - name: se.skltp.ei.EiApplication
      level: INFO
    - name: eiBackendLog
      level: INFO
    - name: eiFrontendLog
      level: INFO
    - name: org.apache.camel
      level: INFO
  rootLoggerLevel: WARN