container:
  repository: docker.drift.inera.se/ntjp/

environment:
  ei-backend:
    variables:
      _default_config_maps:
        - ei-backend-configmap-default
      config_maps:
        # Override to supply your own maps.
      secrets:
        # Override to supply your own secrets.
  ei-frontend:
    variables:
      _default_config_maps:
        - ei-frontend-configmap-default
      config_maps:
        # Override to supply your own maps.
      secrets:
        # Override to supply your own secrets.